
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'eai_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'eai_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  eai_analytics:
    staging:
      +materialized: table
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  raw_data_dir: "data/raw"
  claude_ai_file: "aei_raw_claude_ai_2026-02-05_to_2026-02-12.csv"
  api_file: "aei_raw_1p_api_2026-02-05_to_2026-02-12.csv"